<?php
/**
 * This file is part of the sfSearch package.
 * (c) Carl Vondrick <carl.vondrick@symfony-project.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * A token generated by xfCriterion
 *
 * @package xfSearch
 * @subpackage Criteria
 * @author Carl Vondrick
 */
final class xfCriterionToken
{
  /**
   * The start position
   * 
   * @var int
   */
  private $start;

  /**
   * The end position.
   *
   * @var int
   */
  private $end;

  /**
   * The matched word.
   *
   * @var string
   */
  private $token;

  /**
   * Constructor to set initial values.
   *
   * @param string $token
   * @param int $start
   * @param int $end
   */
  public function __construct($token, $start, $end)
  {
    $this->token = $token;
    $this->start = $start;
    $this->end = $end;
  }

  /**
   * Gets the token word.
   *
   * @returns string
   */
  public function getTokenText()
  {
    return $this->token;
  }

  /**
   * Gets the start position.
   *
   * @returns int
   */
  public function getStart()
  {
    return $this->start;
  }

  /**
   * Gets the end position.
   *
   * @returns int
   */
  public function getEnd()
  {
    return $this->end;
  }
}
